[workspace]
members = ["blur_plugin", "image_processor", "mirror_plugin", "plugin_errors"]
resolver = "3"

[workspace.dependencies]
log = "0.4"
plugin_errors = { path = "./plugin_errors" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
