[package]
name = "blur_plugin"
version = "0.1.0"
edition = "2024"

[lib]
name = "blur"
crate-type = ["cdylib"]

[dependencies]
log = { workspace = true }
plugin_errors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
